apiVersion: v1
kind: Service
metadata:
  name: dynamodb
spec:
  clusterIP: None
  ports:
    - port: 8000
      targetPort: 8000
      name: dynamodb
  selector:
    app: dynamodb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
        - name: dynamodb
          image: amazon/dynamodb-local
          ports:
            - containerPort: 8000

