---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  clusterIP: 10.96.0.2
  ports:
    - port: 3306
      targetPort: 3306
      name: mongo
  selector:
    app: mongo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:4.4.19-rc0
          ports:
            - name: mongo
              containerPort: 3306
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password