#kind: Service
#apiVersion: v1
#metadata:
#  name: redis
#  labels:
#    app: redis
#spec:
#  selector:
#    app: redis
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 6379
#  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          args: ["--appendonly", "yes"]
          ports:
            - name: redis
              containerPort: 6379
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"

