apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: host
      value: mongo-mongodb.default.svc.cluster.local:27017 # Required unless "server" field is set . Example: "mongo-mongodb.default.svc.cluster.local:27017"
    - name: username
      value: admin # Optional. Example: "admin"
    - name: password
      value: gXqPDfsxuN # Optional.