apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.mysql
  version: v1
  metadata:
    - name: connectionString
      value: root:password@tcp(10.96.0.2:3306)/?allowNativePasswords=true
