apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.aws.dynamodb
  version: v1
  metadata:
    - name: table
      value: "dapr_store"
    - name: endpoint
      value: http://10.96.0.3:8000
    - name: region
      value: "eu-west-1" # Optional
    - name: accessKey
      value: "AKIAIOSFODNN7EXAMPLE" # Optional
    - name: secretKey
      value: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" # Optional