apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.mysql
  version: v1
  metadata:
    - name: connectionString
      value: root:RbxmgRRQlZ@tcp(dapr-mysql.default.svc.cluster.local:3306)/
